server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9000
spring:
  datasource:
    username: root
    password: 666666
    url: jdbc:mysql://192.168.1.196:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #日志的相关配置
logging:
  level:
    root: info
#日志的相关配置
spring.activiti.history-level: full
spring.activiti.db-history-used: true
# spring-activiti
# 自动部署验证设置:true-开启（默认）、false-关闭
spring.activiti.check-process-definitions: false